#!/bin/zsh

ABC_CLI_JAVA=${AB_CLI_HOME}/java

DEV_TOOLS=${HOME}/dev-tools
JAVA_TOOLS=${DEV_TOOLS}/java

JAVA_TOOLS_JDK_8=${JAVA_TOOLS}/jdk_8
JAVA_TOOLS_JDK_11=${JAVA_TOOLS}/jdk_11
JAVA_TOOLS_MAVEN=${JAVA_TOOLS}/maven_363